### ISSUE TITLE
Add Privacy Policy and Terms & Conditions

### ISSUE THREAD

**Issue by ipilipos** [cannalogue/CannaReviews#24]
Privacy Policy / Terms&Conditions:

[CannaReviews.Terms.Conditions.txt](https://github.com/cannalogue/CannaReviews/files/2672317/CannaReviews.Terms.Conditions.txt)

[CannaReviews privacy policy.txt](https://github.com/cannalogue/CannaReviews/files/2661136/CannaReviews.privacy.policy.txt)

Please use your own discretion for design, simple is okay.

**Comment by zhaolongli0724** [comment]
1. Can you get a PDF version of the txt?
2. Does the T and C need to be shown in sign up?

**Comment by zhaolongli0724** [comment]
@ipilipos

**Comment by ipilipos** [comment]
Section 10 of Terms & Conditions isn't formatted with bullet points (like Section 11), 
(10.1 -> 10.5)

![image](https://user-images.githubusercontent.com/42971865/49945782-9c55ac80-febb-11e8-9185-771080bef64e.png)

**Comment by zhaolongli0724** [comment]
As discussed, the fine tuning of the content will be after story #38 done. QA this page for now.
